let quest_cards = [{
  "﻿Expansion": "Base",
  "Quest Name": "Explore Ahghairon's Tower",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take an action that provides any mage, also draw an Intrigue card"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Obtain Builders' Plans",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Once per turn you may assign a worker to a building in the Builder's Hall.  You immediately use the effect of the building as though you controlled it."
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Bolster Griffon Cavalry",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "4",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take an action that provides any warriors, also take a warrior from supply and place it in your Tavern"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Produce Miracle For The Masses",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "5",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Once per round, whenever you take an action that provides any clerics, you can also replace a warrior, rogue, or mage in your Tavern with a cleric"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Study in the Librarium",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "2",
  "cost-mage": "5",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "11",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "3.75",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "After you take an action that allows you to play any intrigue card, draw an intrigue card.  You can play that card immediately without taking an action."
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Seize Citadel of the Bloody Hand",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Quest you may return any resource used on that quest"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Defend The Tower Of Luck",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "0",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "1",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "At the start of each round, take any from the supply and place it in your Tavern"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Recruit Lieutenant",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "5",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "0",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Add the Lieutenant to your pool of Agents for the rest of the game"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Defend the Lanceboard Room",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "3",
  "cost-rogue": "6",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "12",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "8",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Fence Goods For Duke Of Darkness",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take an action that provides any rogues, also take 2 Gold from the supply"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Thin The City Watch",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "4",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Establish Temple to Ibrandul",
  "Quest Type": "Piety",
  "cost-cleric": "3",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "11",
  "reward-cleric": "1",
  "reward-warrior": "1",
  "reward-rogue": "1",
  "reward-mage": "1",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "3.4816",
  "reward-corruption": "",
  "misc.": "Take all quests from Cliffwatch Inn"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Save Kidnapped Nobles",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "6",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "4",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-3",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Recruit For Blackstaff Academy",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "3",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Heal Fallen Gray Hand Soldiers",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "6",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Defend the Yawning Portal",
  "Quest Type": "Warfare",
  "cost-cleric": "3",
  "cost-warrior": "6",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "15",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "2",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Return up to 3 workers to your pool"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Deal With the Black Viper",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "4",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "4",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "As you draw each intrigue card from this quest you may play it immediately"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Recruit for City Watch (+ optional costs)",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "3",
  "reward-rogue": "3",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Banish Evil Spirits",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "5",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "1",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-2",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Wake the Six Sleepers",
  "Quest Type": "Warfare",
  "cost-cleric": "3",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "6",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Train Castle Guards",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever a player takes the first marker you and that player also take a warrior"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Resurrect Dead Wizards",
  "Quest Type": "Arcana",
  "cost-cleric": "3",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "3",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Survive Arcturia's Transformation",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "6",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "6",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Investigate Thayan Vessel",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "2",
  "reward-gold": "",
  "reward-intrigue": "2",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Donate to the City",
  "Quest Type": "Commerce",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-3",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Institute Reforms",
  "Quest Type": "Piety",
  "cost-cleric": "4",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-3",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Threaten the Builders' Guilds",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "4",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Immediately put all face-up Buildings in Builder's Hall in play under your control at no cost."
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Seal and Entrance to Skullport",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-3",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Recruit Paladins For Tyr",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "4",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "10",
  "reward-cleric": "3",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Rescue Clerics of Tymora",
  "Quest Type": "Piety",
  "cost-cleric": "",
  "cost-warrior": "6",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "3",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Steal From House Adarbrent",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "6",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Take Over Rival Organization",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "2",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "6",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "4",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Steal Spellbook From Silverhand",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "2",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "7",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "2",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Steal Gems from the Bone Throne",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "7",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "10",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Establish New Merchant Guild",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Commerce Quest, you score 2 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Protect The House Of Wonder",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Piety Quest, you score 2 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Quell Mercenary uprising",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Warfare Quest, you score 2 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Place A Sleeper Agent In Skullport",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "0",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you play Intrigue, you score 2 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Research Chronomancy",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "4",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "1",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "return 1 of your assigned Agents to your pool"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Safeguard Eltorchul Mage",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "4",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "2",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Perform The Penance Of Duty",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "12",
  "reward-cleric": "1",
  "reward-warrior": "1",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Expose Cult Corruption",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "4",
  "reward-cleric": "2",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Train Bladesingers",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "3",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "4",
  "reward-cleric": "",
  "reward-warrior": "1",
  "reward-rogue": "",
  "reward-mage": "1",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Sponsor Bounty Hunters",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "6",
  "vp": "12",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take a Commerce Quest, take 4 gold"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Sanctify a Desecrated Temple",
  "Quest Type": "Piety",
  "cost-cleric": "4",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take a Piety Quest take a cleric"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Host Festival For Sune",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "9",
  "reward-cleric": "2",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Renew Guards and Wards",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-2",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Rescue of Victim from the Skulls",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "1",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-1",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Deliver Weapons To Selune's Temple",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "4",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "9",
  "reward-cleric": "2",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Patrol Dock Ward",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "3",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "4",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Placate The Walking Statue",
  "Quest Type": "Commerce",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "draw one Building from the stack and put it into play under your control at no cost"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Diplomatic Mission to Suzail",
  "Quest Type": "Piety",
  "cost-cleric": "3",
  "cost-warrior": "3",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "3",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "You may complete face-up quests at Cliffwatch Inn as though they were active quests."
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Explore Trobriand's Graveyard",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "3",
  "cost-mage": "4",
  "cost-any": "",
  "cost-gold": "6",
  "vp": "40",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Ransack Whitehelm's Tomb",
  "Quest Type": "Commerce",
  "cost-cleric": "2",
  "cost-warrior": "3",
  "cost-rogue": "4",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "10",
  "vp": "40",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Plunder the Island Temple",
  "Quest Type": "Piety",
  "cost-cleric": "5",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "40",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Battle in Muiral's Gauntlet",
  "Quest Type": "Warfare",
  "cost-cleric": "2",
  "cost-warrior": "7",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "40",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Uncover Drow Plot",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "5",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "18",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-2",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Prison Break",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "14",
  "reward-cleric": "",
  "reward-warrior": "2",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "immediately play Intrigue without taking an action"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Lure Artisans Of Mirabar",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "4",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "put one Building from Builder's Hall into play under your control at no cost"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Bribe The Shipwrights",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take an action that provides any Gold, also take a rogue from the supply and place it in your Tavern"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Ally with Xanathar's Guild",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "5",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take a Skullduggery Quest, take a rogue"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Recover the Flame of the North",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "5",
  "cost-rogue": "3",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "3",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take a Warfare Quest, take a warrior"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Retrieve Ancient Artifacts",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "1",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "11",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Spy On The Lighthouse",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "3",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "6",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Eliminate Vampire Coven",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "2",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "11",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Defeat Uprising From Undermountain",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "3",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "11",
  "reward-cleric": "",
  "reward-warrior": "2",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Deliver An Ultimatum",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "4",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "11",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Impersonate Adarbrent Noble",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "18",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "2",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Investigate Aberrant Infestation",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "1",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Infiltrate Builder's Hall",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you buy a Building, you score 4 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Infiltrate Halaster's Circle",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "5",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "25",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Ally With House Thann",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "8",
  "vp": "25",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Create A Shrine To Oghma",
  "Quest Type": "Piety",
  "cost-cleric": "5",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "25",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Establish Shadow Thieves' Guild",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "8",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "25",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Bolster City Guard",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "9",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "25",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Expose Red Wizards' Spies",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "2",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "1",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Domesticate Owlbears",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "1",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "2",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Recruit Academy Castoffs",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to Blackstaff Tower you can take a mage and a corruption"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Fund Alchemical Research",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "1",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "12",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "3",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Recruit for City Watch (base card)",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Extort Aurora",
  "Quest Type": "Commerce",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to Aurora's Realms Shop you can take another 4 gold and corruption"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Seal Gate To Cyric's Realm",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Give Honor to Mask",
  "Quest Type": "Piety",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to the Plinth you may take an additional cleric and corruption"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Raid On Undermountain",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "2",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Procure Stolen Goods",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "6",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "2",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Expand Guild Activities",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to the Grinning Lion Tavern you can take an additional rogue and corruption"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Confront The Xanathar",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "2",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "2",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Destroy a Temple of Selvetarm (+ optional costs)",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "6",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Ambush Artor Morlin",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "3",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Raid Orc Stronghold",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "4",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "4",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Fix the Champion's Games",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "3",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to the Field of Triumph you can take another 2 warriors and a corruption"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Improve Prison Security",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-3",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Break Into Blackstaff Tower",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "7",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "9",
  "vp": "40",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Survive a Meeting With Halaster",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "4",
  "cost-gold": "",
  "vp": "15",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Draw an intrigue card for each mage you used to complete this quest"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Root Out Loviatar's Faithful",
  "Quest Type": "Piety",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "4",
  "cost-gold": "",
  "vp": "15",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": " +2 points for each cleric used to fulfill this quest"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Repel Seawraiths",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "4",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "15",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "2",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Unleaseh Crime Spree (+ optional costs)",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "5",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "22",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Defame Rival Business",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you purchase a building, you can remove a corruption from your tavern and place it on an action space"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Fund Pilgrimage of Waukeen",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "2",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "16",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Convert A Noble To Lathander",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "1",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "0.8704",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Shelter Zhentarim Agents",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "3",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "16",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "1",
  "misc.": "Once on any turn, whenever you gain any corruption draw an intrigue card"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Uncover Forbidden Lore",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "2",
  "cost-mage": "3",
  "cost-any": "",
  "cost-gold": "",
  "vp": "17",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to Waterdeep Harbor you can play up to 2 additional intrigue cards, if you do take a corruption"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Build A Reputation In Skullport",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "1",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Destroy a Temple of Selvetarm (base card)",
  "Quest Type": "Warfare",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Establish Cult Cell",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "2",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "3",
  "vp": "18",
  "reward-cleric": "",
  "reward-warrior": "2",
  "reward-rogue": "",
  "reward-mage": "1",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "1",
  "reward-quest": "",
  "reward-corruption": "3",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Sanctify Temple to Oghmaa",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "18",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Enter the Tower of Seven Woes",
  "Quest Type": "Piety",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "",
  "cost-any": "7",
  "cost-gold": "",
  "vp": "19",
  "reward-cleric": "3",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "4",
  "misc.": ""
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Unleaseh Crime Spree (base card)",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "12",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Optional cost to get different rewards"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Discover Hidden Temple Of Lolth",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "0.8704",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Form An Alliance With The Rashemi",
  "Quest Type": "Piety",
  "cost-cleric": "2",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "0.8704",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Assassinate Rivals",
  "Quest Type": "Warfare",
  "cost-cleric": "",
  "cost-warrior": "4",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "",
  "vp": "16",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "2",
  "misc.": "Each opponent returns any resource"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Study The Illusk Arch",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Arcana Quest, you score 2 VP"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Bury the Bodies",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "20",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "2",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Swindle the Builder's Guilds",
  "Quest Type": "Skullduggery",
  "cost-cleric": "1",
  "cost-warrior": "2",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "13",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "3",
  "misc.": "Put 2 face up Buildings in the Builder's Hall in play under your control"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Send Aid To The Harpers",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "1",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "15",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "choose an opponent to gain 4 gold"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Loot The Crypt Of Chauntea",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "7",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "1",
  "reward-quest": "0.4",
  "reward-corruption": "",
  "misc.": ""
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Pay Fines",
  "Quest Type": "Commerce",
  "cost-cleric": "1",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "4",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "-2",
  "misc.": ""
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Establish Harpers Safe House",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "2",
  "cost-rogue": "3",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "2",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "+2 for each building you control"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Establish Wizard Academy",
  "Quest Type": "Arcana",
  "cost-cleric": "1",
  "cost-warrior": "1",
  "cost-rogue": "3",
  "cost-mage": "3",
  "cost-any": "",
  "cost-gold": "",
  "vp": "12",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you take an Arcana Quest, take a mage from the supply"
}, {
  "﻿Expansion": "Skullport",
  "Quest Name": "Protect Converts to Eilistraee",
  "Quest Type": "Piety",
  "cost-cleric": "3",
  "cost-warrior": "2",
  "cost-rogue": "",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "",
  "vp": "10",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you return any corruption you may return another corruption"
}, {
  "﻿Expansion": "Undermountain",
  "Quest Name": "Impersonate Tax Collector",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "1",
  "cost-rogue": "4",
  "cost-mage": "1",
  "cost-any": "",
  "cost-gold": "5",
  "vp": "9",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you assign a worker to a building you control, you also gain the owner benefit"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Install A Spy In Castle Waterdeep",
  "Quest Type": "Skullduggery",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "4",
  "cost-mage": "",
  "cost-any": "",
  "cost-gold": "4",
  "vp": "8",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Whenever you complete a Skullduggery Quest, you score 2 VP"
}, {
  "﻿Expansion": "Base",
  "Quest Name": "Recover The Magister's Orb",
  "Quest Type": "Arcana",
  "cost-cleric": "",
  "cost-warrior": "",
  "cost-rogue": "3",
  "cost-mage": "2",
  "cost-any": "",
  "cost-gold": "",
  "vp": "6",
  "reward-cleric": "",
  "reward-warrior": "",
  "reward-rogue": "",
  "reward-mage": "",
  "reward-any": "",
  "reward-gold": "",
  "reward-intrigue": "",
  "reward-quest": "",
  "reward-corruption": "",
  "misc.": "Once per round, you can assign an Agent to a space containing an opponent's Agent"
}];

export {quest_cards};